import { GAME_DAY_SECONDS as DAY } from './items';
import type { ResourceNodeDef } from './types';

export const NODE_LIST: ResourceNodeDef[] = [
  { id: 'palm', name: 'Palm Tree', action: 'chop', minTier: 1, hp: 70, radius: 0.35, height: 9, solid: true, respawnSeconds: DAY * 3,
    yields: [{ item: 'log', min: 2, max: 3 }, { item: 'palm_frond', min: 2, max: 4 }, { item: 'coconut', min: 0, max: 2 }],
    perHit: [{ item: 'stick', qty: 1, chance: 0.15 }] },
  { id: 'hardwood', name: 'Ironwood Tree', action: 'chop', minTier: 1, hp: 120, radius: 0.55, height: 12, solid: true, respawnSeconds: DAY * 4,
    yields: [{ item: 'log', min: 3, max: 4 }, { item: 'resin', min: 1, max: 2 }, { item: 'stick', min: 1, max: 3 }] },
  { id: 'fiber_bush', name: 'Fiber Shrub', action: 'gather', minTier: 0, hp: 1, radius: 0.5, height: 1, solid: false, respawnSeconds: DAY,
    yields: [{ item: 'fiber', min: 2, max: 4 }, { item: 'stick', min: 0, max: 1 }] },
  { id: 'berry_bush', name: 'Berry Bush', action: 'gather', minTier: 0, hp: 1, radius: 0.6, height: 1.1, solid: false, respawnSeconds: DAY * 1.5,
    yields: [{ item: 'berries', min: 2, max: 4 }, { item: 'berry_seed', min: 0, max: 1, chance: 0.4 }] },
  { id: 'wild_taro', name: 'Wild Taro', action: 'gather', minTier: 0, hp: 1, radius: 0.5, height: 0.8, solid: false, respawnSeconds: DAY * 2,
    yields: [{ item: 'taro_raw', min: 1, max: 2 }, { item: 'taro_seed', min: 1, max: 1 }] },
  { id: 'wild_aloe', name: 'Wild Aloe', action: 'gather', minTier: 0, hp: 1, radius: 0.4, height: 0.6, solid: false, respawnSeconds: DAY * 2,
    yields: [{ item: 'aloe', min: 1, max: 2 }, { item: 'aloe_seed', min: 0, max: 1, chance: 0.5 }] },
  { id: 'wild_flax', name: 'Wild Flax', action: 'gather', minTier: 0, hp: 1, radius: 0.4, height: 0.9, solid: false, respawnSeconds: DAY,
    yields: [{ item: 'fiber', min: 3, max: 5 }, { item: 'flax_seed', min: 0, max: 1, chance: 0.5 }] },
  { id: 'rock', name: 'Rock Outcrop', action: 'mine', minTier: 1, hp: 90, radius: 1.1, height: 1.4, solid: true, respawnSeconds: DAY * 3,
    yields: [{ item: 'stone', min: 3, max: 5 }, { item: 'flint', min: 0, max: 2 }], perHit: [{ item: 'stone', qty: 1, chance: 0.2 }] },
  { id: 'iron_vein', name: 'Ore Vein', action: 'mine', minTier: 2, hp: 160, radius: 1.2, height: 1.6, solid: true, respawnSeconds: DAY * 5,
    yields: [{ item: 'iron_ore', min: 2, max: 4 }, { item: 'stone', min: 1, max: 3 }] },
  { id: 'obsidian_rock', name: 'Obsidian Spire', action: 'mine', minTier: 2, hp: 140, radius: 0.9, height: 2.2, solid: true, respawnSeconds: DAY * 5,
    yields: [{ item: 'obsidian', min: 1, max: 3 }, { item: 'flint', min: 1, max: 2 }] },
  { id: 'clay_bank', name: 'Clay Bank', action: 'dig', minTier: 1, hp: 50, radius: 1.0, height: 0.4, solid: false, respawnSeconds: DAY * 2,
    yields: [{ item: 'clay', min: 3, max: 5 }] },
  { id: 'loose_stone', name: 'Loose Stone', action: 'gather', minTier: 0, hp: 1, radius: 0.25, height: 0.2, solid: false, respawnSeconds: DAY,
    yields: [{ item: 'stone', min: 1, max: 1 }, { item: 'flint', min: 0, max: 1, chance: 0.2 }] },
  { id: 'loose_stick', name: 'Fallen Branch', action: 'gather', minTier: 0, hp: 1, radius: 0.3, height: 0.1, solid: false, respawnSeconds: DAY * 0.75,
    yields: [{ item: 'stick', min: 1, max: 2 }] },
  { id: 'driftwood', name: 'Driftwood', action: 'gather', minTier: 0, hp: 1, radius: 0.6, height: 0.3, solid: false, respawnSeconds: DAY,
    yields: [{ item: 'stick', min: 2, max: 3 }, { item: 'log', min: 0, max: 1, chance: 0.4 }] },
  { id: 'beach_shell', name: 'Shell', action: 'gather', minTier: 0, hp: 1, radius: 0.2, height: 0.1, solid: false, respawnSeconds: DAY * 0.75,
    yields: [{ item: 'shell', min: 1, max: 2 }] },
  { id: 'fallen_coconut', name: 'Fallen Coconut', action: 'gather', minTier: 0, hp: 1, radius: 0.25, height: 0.25, solid: false, respawnSeconds: DAY,
    yields: [{ item: 'coconut', min: 1, max: 1 }] },
  { id: 'coral', name: 'Brain Coral', action: 'mine', minTier: 1, hp: 40, radius: 0.8, height: 0.9, solid: true, underwater: true, respawnSeconds: DAY * 2,
    yields: [{ item: 'coral', min: 2, max: 3 }, { item: 'shell', min: 0, max: 2 }] },
  { id: 'kelp', name: 'Kelp Stand', action: 'gather', minTier: 0, hp: 1, radius: 0.4, height: 3, solid: false, underwater: true, respawnSeconds: DAY,
    yields: [{ item: 'kelp', min: 2, max: 3 }] },
  { id: 'oyster', name: 'Oyster Bed', action: 'gather', minTier: 0, hp: 1, radius: 0.5, height: 0.3, solid: false, underwater: true, respawnSeconds: DAY * 2,
    yields: [{ item: 'shell', min: 1, max: 2 }, { item: 'pearl', min: 1, max: 1, chance: 0.12 }] },
  { id: 'scrap_pile', name: 'Wreck Debris', action: 'mine', minTier: 1, hp: 60, radius: 1.0, height: 0.8, solid: true, respawnSeconds: DAY * 4,
    yields: [{ item: 'scrap_metal', min: 1, max: 3 }, { item: 'cloth', min: 0, max: 2 }, { item: 'copper_wire', min: 0, max: 1, chance: 0.3 }] },
];

export const NODES: Readonly<Record<string, ResourceNodeDef>> = Object.fromEntries(NODE_LIST.map((n) => [n.id, n]));
