// Milestones shown as toasts the first time they happen in a world.
export const ADVANCEMENTS = {
  log: ['First Timber', 'Collect a log'],
  crafting_table: ['Workbench', 'Craft a crafting table'],
  pickaxe: ['Break Ground', 'Craft a pickaxe'],
  furnace: ['Fire It Up', 'Craft a furnace'],
  iron: ['Metalworker', 'Smelt an iron ingot'],
  diamond: ['Glittering Find', 'Pick up a diamond'],
  armor: ['Suit Up', 'Put on a piece of armor'],
  bread: ['Baker', 'Bake a loaf of bread'],
  farm: ['Green Thumb', 'Plant a crop'],
  hostile: ['Night Watch', 'Defeat a hostile creature'],
  bow: ['Sharpshooter', 'Hit a target with an arrow'],
  sleep: ['Sweet Dreams', 'Sleep through the night'],
  trade: ['Fair Trade', 'Trade with a settler'],
  breed: ['Growing Family', 'Breed two animals'],
  underworld: ['Into the Depths', 'Enter the Underworld'],
  enchant: ['Arcane Arts', 'Enchant an item'],
  level: ['Experienced', 'Reach experience level 5'],
  fish: ['Patient Angler', 'Catch something with a fishing rod'],
  potion: ['Local Alchemist', 'Brew a potion'],
  spark: ['Live Wire', 'Light a spark lamp with a circuit'],
  cart: ['On the Rails', 'Ride a minecart'],
  boat: ['Set Sail', 'Row a boat'],
  gate: ['Starlit Threshold', 'Open a star gate'],
  void: ['Beyond the Stars', 'Enter the Void'],
  wyrm: ['Wyrmslayer', 'Defeat the Void Wyrm'],
  glider: ['Wings of the Void', 'Glide with a glider'],
  map: ['Cartographer', 'Make a map'],
  blaster: ['Pew Pew', 'Fire a photon blaster'],
  tame: ['Best Friends', 'Tame an animal'],
  golem: ['Guardian Maker', 'Build a sentinel'],
  beacon: ['Light the Way', 'Power a beacon'],
  biome: ['Explorer', 'Visit a jungle, the badlands or the mushroom fields'],
  citadel: ['Into the Deep', 'Find a tide citadel'],
  rocket: ['Afterburner', 'Boost a glide with a sky rocket'],
  honey: ['Sweet Tooth', 'Collect honey or honeycomb from a hive'],
  starsteel: ['Forged in the Stars', 'Upgrade diamond gear with starsteel'],
  raid: ['Village Hero', 'Defend a village from a raid'],
  parrot: ['Shoulder Companion', 'Carry a parrot on your shoulder'],
  wax: ['Waxed Up', 'Seal copper with honeycomb so it never weathers'],
  ancient_city: ['Deeper Than Dark', 'Find an ancient city far underground'],
  listener: ['Hush', 'Hear the Listener rise, and live'],
};
